<footer class="main-nav-footer">
<menu class="social-links">
<a href="xxxhttps://www.facebook.com/sarah.appleby" target="_blank">&#xe027;</a>
<a href="xxhttps://instagram.com/oksarahappleby/" target="_blank">&#xe100;</a>
<a href="https://www.artsy.net/shulamit-gallery" target="_blank" class="artsty-icon">ARTSY</a>
</menu>
<address>
<p><a href="https://www.google.com/maps/place/17+N+Venice+Blvd,+Venice,+CA+90291/@33.9845967,-118.4710927,17z/data=!3m1!4b1!4m2!3m1!1s0x80c2babbcf9d3253:0xee9f87c131a4f212" target="_blank">17 North Venice Blvd<br>
Venice California, 90291<br>
310.281.0961</a><br>
<a href="mailto:info@shulamitgallery.com" target="_blank">info@shulamitgallery.com</a></p>
</address>
</footer>